<?php

namespace BBBundle\Repository;

/**
 * AdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDistinct()
    {
        return $this->createQueryBuilder('a')
            ->select('a.ip')->distinct()
            ->getQuery()
            ->getResult();
    }

    public function getOnMonth()
    {
        return $this->createQueryBuilder('a')
            ->where("a.visited_at > DATE_ADD(CURRENT_DATE(),(-1),'MONTH')")
            ->getQuery()
            ->getResult();
    }

    public function getOnWeek()
    {
        return $this->createQueryBuilder('a')
            ->where("a.visited_at > DATE_ADD(CURRENT_DATE(),(-7),'DAY')")
            ->getQuery()
            ->getResult();
    }
}
