<?php

namespace BBBundle\Repository;


/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommentsNotAllowed()
    {
        $q = $this->getEntityManager()
            ->createQuery('select c,d from BBBundle:Comments c INNER JOIN c.draw d WHERE c.isAllowed=0 ORDER BY c.createdAt DESC ');
        return $q->getResult();
    }


    public function findCommentsAllowed($drawid)
    {
        $q = $this->getEntityManager()
            ->createQuery('select c,d from BBBundle:Comments c INNER JOIN c.draw d WHERE c.isAllowed=1 AND c.draw = :drawid ORDER BY c.createdAt DESC ')->setParameter('drawid',$drawid);
        return $q->getResult();
    }
}
