<?php

namespace BBBundle\Repository;

use BBBundle\Entity\Draw;

/**
 * DrawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrawRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDrawByPost(){


        $q = $this->getEntityManager()
            ->createQuery("select d from BBBundle:Draw d where d.category = '1' ORDER BY d.createdAt");

        return $q->getResult();


        /*$q = $this->createQueryBuilder('draw')
            ->where('draw.category = :post')
            ->join('draw.category', 'category')
            ->join('draw.picture','picture')
//            ->setParameter('post',$category)
            ->addSelect('category', 'picture');*/

//        return $q->getQuery()->getResult();

    }

    public function findDCommentsNotAllowed()
    {
        $q = $this->getEntityManager()
            ->createQuery('select d,c from BBBundle:Draw d INNER JOIN d.comments c WHERE c.isAllowed=FALSE ORDER BY c.createdAt DESC ');
        return $q->getResult();
    }

    public function findDrawByDoodle(){
        $q = $this->getEntityManager()
            ->createQuery("select d,c from BBBundle:Draw d where d.category = '2' ORDER BY d.createdAt DESC ");

        return $q->getResult();
    }

    public function increasePouces(){

        $q = $this->getEntityManager()
            ->createQuery("update BBBundle:Draw d set d.pouces = d.pouces + 1 ");

        return $q->getResult();
    }

    public function findPouces(Draw $draw){

        return $this->createQueryBuilder('d')
            ->select('d.pouces')
            ->where('d = :draw')
            ->setParameter('draw', $draw)
            ->getQuery()
            ->getResult();
    }
}
