<?php

namespace BBBundle\Repository;

/**
 * VisitorPaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorPaintRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function currentMonthPaints(){

        $now = new \DateTime('now');
        $n  = $now->format('Y-m-d');
        $l = substr($n, 0, 7);
        return $this->createQueryBuilder('p')
                    ->where('SUBSTRING(p.createdAt, 1, 7) = :date')
                    ->setParameter('date', $l)
                    ->getQuery()
                    ->getResult();
    }
}
