<?php

namespace BBBundle\Repository;

/**
 * WinnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinnerRepository extends \Doctrine\ORM\EntityRepository
{
}
